### ISSUE TITLE
What about multi-line comments?

### ISSUE THREAD

**Issue by bichanna** [bichanna/slap#23]
What about multi-line comments? Would you like one in SLAP?

**Comment by bichanna** [comment]
Maybe something like this?
```
##
This is a multi-line comment.
##
```
Alternatively this?
```
#{
Comment!
}#
```

**Comment by bichanna** [comment]
Well, there's no response, so I decided to use the second one. See here [f4f96ba](https://github.com/bichanna/slap/commit/f4f96ba270304ee9ac70d2791c3f32dc34618792).

**Comment by GalaxianMonster** [comment]
I guess second one is better.
