### ISSUE TITLE
List assignment is broken

### ISSUE THREAD

**Issue by bichanna** [bichanna/slap#28]
code:
```
let list = [1, 3, 4];
list@[0] = "string";
println(list);
```
error:
```

1: let list = [1, 3, 4];
2: list@[0] = "string";
3: println(list);

RuntimeError: '' is not defined
```

**Comment by GalaxianMonster** [comment]
Try working on test scripts to just like the creator of lox does. It might be helpful since this language is new. Like variables not being able to have numbers(and returns a wrong error), and more.

**Comment by bichanna** [comment]
I will that :D

**Comment by bichanna** [comment]
But this bug is fixed!
