### ISSUE TITLE
Make SLAP extendable

### ISSUE THREAD

**Issue by GalaxianMonster** [bichanna/slap#30]
**Is your feature request related to a problem? Please describe.**
Nope, not related to a problem.

**Describe the solution you'd like**
I do not really have current solutions to really solve, but the basic idea is to call a function from a shared object file (*.so or *.dll) and call it.
As for this shared object file to be communicate with the program SLAP needs an API just like python does.

**Describe alternatives you've considered**
I think you could use libffi(I don't know if it can work on Nim or can really help with this feature).

**Additional context**
None.

**Comment by bichanna** [comment]
SLAP is a tree-walker, so it does not spit out anything like a file of bytecode.
Correct me if I'm wrong.

Or did you mean something else?

**Comment by GalaxianMonster** [comment]
This isn't related to bytecode. Also, what I mean is that SLAP should have an interface so that we could make native libraries for slap instead of preadding it to the interpreter. "Native Libraries" are basically shared object files.

**Comment by bichanna** [comment]
Sorry for my misunderstanding.
I think that's a good idea. So, I might implement that after stabilizing the current state of SLAP.

**Comment by GalaxianMonster** [comment]
Its okay.
