### ISSUE TITLE
Need help with build.bat

### ISSUE THREAD

**Issue by bichanna** [bichanna/slap#5]
I know almost nothing about Windows. So, please help me write this build.bat file.

**Comment by GalaxianMonster** [comment]
Sorry I also don't know a lot of stuff about Windows, I guess you need to research about it.

**Comment by bichanna** [comment]
I'll research it.
Do you know how I can test my bat commands? (I'm using Mac and sometimes Linux)

**Comment by GalaxianMonster** [comment]
I might be able to test it on my computer.

**Comment by bichanna** [comment]
I haven't written that but I added a workflow for Windows: f312961ce04e966f79eaa45a02417002e7d47075.

**Comment by GitbyteMaster** [comment]
I actually know a bit, and am willing to help.
